# .github/workflows/scrape_to_hf.yml
name: Scrape Nationale Assemblee PDFs → HF

on:
  # Manual trigger with optional script choice
  workflow_dispatch:
    inputs:
      script:
        description: "Python script to run"
        required: true
        default: "nationale_assemblee_scraper_to_hf.py"
        type: choice
        options:
          - nationale_assemblee_scraper_to_hf.py
          - sris_scrape_upload_hf.py
          - sru_scraper.py

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run selected scraper
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python "${{ inputs.script }}"
